name: Check Pull Request

on:
  pull_request:
    branches:
      - main

env:
  PNPM_CACHE_PATH: ${{ github.workspace }}/.pnpm-store

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup tools
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

      - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ${{ env.PNPM_CACHE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm config set store-dir ${{ env.PNPM_CACHE_PATH }}
          pnpm install

      - name: Build dependencies packages
        run: pnpm -F @sun-yryr/queot-planparser build

      - name: Check
        run: pnpm -r check

      - name: Test
        run: pnpm -r test
