name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true
  PNPM_CACHE_PATH: ${{ github.workspace }}/.pnpm-store

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup tools
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

      # npm trusted publishing requires npm v11 (らしい)
      - name: Update npm to v11
        run: npm install -g npm@^11.7.0

      - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ${{ env.PNPM_CACHE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm config set store-dir ${{ env.PNPM_CACHE_PATH }}
          pnpm install

      - name: Build
        run: pnpm -r build

      - name: Create and publish versions
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          commit: "chore: Release packages"
          title: ":tada: Release packages"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
